// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcbDaAnl4qyhHnDfj-Cz2MIgQ8PacUvw',
    appId: '1:109221955317:web:86d02b2720ed04312427bc',
    messagingSenderId: '109221955317',
    projectId: 'queue-f577d',
    authDomain: 'queue-f577d.firebaseapp.com',
    databaseURL: 'https://queue-f577d-default-rtdb.firebaseio.com',
    storageBucket: 'queue-f577d.appspot.com',
    measurementId: 'G-4HWGD38FE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOBEot4YyBBw952yg90qyMEb1DpCLBKA',
    appId: '1:109221955317:android:a389def32b8436e72427bc',
    messagingSenderId: '109221955317',
    projectId: 'queue-f577d',
    databaseURL: 'https://queue-f577d-default-rtdb.firebaseio.com',
    storageBucket: 'queue-f577d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4onbQONAElmtXQ9MnQi1b1Ui0aL8iCK4',
    appId: '1:109221955317:ios:c89ba27eba3f80982427bc',
    messagingSenderId: '109221955317',
    projectId: 'queue-f577d',
    databaseURL: 'https://queue-f577d-default-rtdb.firebaseio.com',
    storageBucket: 'queue-f577d.appspot.com',
    iosClientId: '109221955317-bp4e3dbfjm7lqcq6lljg3er80pknn0ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.queue',
  );
}
